### PR TITLE
Main

### PR DESCRIPTION
**Pull request by AlfredoElizarraras**
Targets Achieved
General Requirements

Add descriptive README file to your repository.
Use meaningful names for your Pull Requests and add a short summary of its content.
Use descriptive commit messages.
Do not commit files that are not related to the project. Instead, add them to .gitignore file.
Do not commit inline comments.

Use stickler for checks.

Other Requirements

Keep your code clean.
Remember to use semantic HTML.
Validate your HTML markup.

Use stylelint to lint CSS files.

Project Specific

Align all elements with flex and float.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# This is really amazing! @AlfredoElizarraras :rocket: 
You have done an exceptional job building this, your readme is beautiful, your code is well written and semantically correct and you have no linter errors. Keep this energy moving forward!

Please address this one issue and submit for a re-review:
* Your search bar looks great and you have a really cool effect on it, however, its too much to the right of the surrounding box unlike the other links in the navbar. Make it central so your project can shine like it should! :+1: :1st_place_medal:

**Comment by AlfredoElizarraras** [comment]
Thanks for your so cool feedback, I will continue doing it well!
I fix centering the input. =)

**Review by nikasulo — APPROVED** [review]
# You've done it! @AlfredoElizarraras ! :medal_military: 
Please merge and carry on :rocket:. See you at the top :handshake:.

**Comment by AlfredoElizarraras** [comment]
*Thanks you!* 😃

**Pull request merged**
